### PR TITLE
Add Replicate demo

### PR DESCRIPTION
**Pull request by ArielReplicate**
Hey ! 👋 

Thanks for another great project!

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can run your model! 
View it here: https://replicate.com/arielreplicate/scalable_diffusion_with_transformers

Replicate also have an API, so people can easily run your model from their code:

```python
import replicate
model = replicate.models.get("[arielreplicate/scalable_diffusion_with_transformers]")
model.predict(...)
```

If you'd like to modify the Replicate page, let me know and I can transfer ownership to your account.

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by wpeebles** [comment]
Super cool, thanks for adding it!

**Comment by ArielReplicate** [comment]
Hi @wpeebles I'm happy you liked the demo.
Sure, I'm currently working on finding out whether Replicate had already signed the CLA.

**Comment by ArielReplicate** [comment]
Hi, the CLA is signed by Replicate.
You can merge now.

**Comment by wpeebles** [comment]
Thanks @ArielReplicate! Sorry for the delay in responding. I went ahead and added the Replicate demo URL to the README. Just to keep the main branch of the repo as minimalist as possible, I think it might be good to leave the demo files in this PR for people to use. Thanks again for setting-up the cool demo!

**Pull request closed without merging**
